services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: config-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-configsvc-alpha}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-configsvc-alpha}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

